### ISSUE TITLE
splunk.service  failed CentOS 7.7.1908

### ISSUE THREAD

**Issue by LawHsing** [johnmcgovern/ansible-splunk-base#1]
![image](https://user-images.githubusercontent.com/46511284/78113585-895d4780-7432-11ea-88fb-9cc0949a9210.png)

![image](https://user-images.githubusercontent.com/46511284/78113553-7c405880-7432-11ea-8d53-5ccf2d16da6c.png)

**Comment by LawHsing** [comment]
![image](https://user-images.githubusercontent.com/46511284/78114960-a98e0600-7434-11ea-8c32-0d6cd36afd1a.png)

When I run install.yml, I get an error.
I understand this playbook is to install splunk, not splunkforwarder

**Comment by johnmcgovern** [comment]
@LawHsing Do you know if there was ever a Universal Forwarder running on this system? It looks like the UF lefts its own file in /etc/rc.d/init.d/splunk. Thinking out loud, it may be a good idea to implement a check for this condition in the install playbook. I will have to think through that.

**Comment by johnmcgovern** [comment]
I was able to replicate this error by first installing the UF, shutting down the process, and then installing core Splunk. The issue is I don't want to forcibly check for a remove a UF install for safety reasons. Screenshot below.

<img width="1023" alt="Screenshot_4_3_20__6_39_PM" src="https://user-images.githubusercontent.com/2053256/78416035-a3d22500-75da-11ea-9606-204ee8817e5f.png">

**Comment by LawHsing** [comment]
Yes, I installed UF on this system before.  I found a new system  just installed and it can be installed normally, thank you~

**Comment by johnmcgovern** [comment]
Glad to hear that this worked. I hope the project proves useful to you!
